server:
  port: 18082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://169.254.56.69:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://locolhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/guli-oms
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
    host: 192.168.56.10

feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:/mapper/oms/*.xml
  type-aliases-package: com.atguigu.gmall.oms.entity
  global-config:
    db-config:
      id-type: auto